services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - inventory_data:/var/lib/postgresql/data
volumes:
  inventory_data:

      