services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - inventory_data:/var/lib/postgresql/data
#  api-svc:
#    build:
#      context: .
#      dockerfile: API/Dockerfile
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=http://+:80
#      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=Inventory
#    ports:
#      - 7001:80
#    depends_on:
#      - postgres
volumes:
  inventory_data:


      