@API_HostAddress = http://localhost:7001

### Makes
### Get all makes
GET {{API_HostAddress}}/api/makes/
Accept: application/json

### Get all makes By Model
GET {{API_HostAddress}}/api/models/byMake/12
Accept: application/json


### Models

GET {{API_HostAddress}}/api/makes/
Accept: application/json

### Products

GET {{API_HostAddress}}/api/products
Accept: application/json
